/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteAttachmentArgs } from "./DeleteAttachmentArgs";
import { AttachmentCountArgs } from "./AttachmentCountArgs";
import { AttachmentFindManyArgs } from "./AttachmentFindManyArgs";
import { AttachmentFindUniqueArgs } from "./AttachmentFindUniqueArgs";
import { Attachment } from "./Attachment";
import { AttachmentService } from "../attachment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Attachment)
export class AttachmentResolverBase {
  constructor(
    protected readonly service: AttachmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "read",
    possession: "any",
  })
  async _attachmentsMeta(
    @graphql.Args() args: AttachmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Attachment])
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "read",
    possession: "any",
  })
  async attachments(
    @graphql.Args() args: AttachmentFindManyArgs
  ): Promise<Attachment[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Attachment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "read",
    possession: "own",
  })
  async attachment(
    @graphql.Args() args: AttachmentFindUniqueArgs
  ): Promise<Attachment | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Attachment)
  @nestAccessControl.UseRoles({
    resource: "Attachment",
    action: "delete",
    possession: "any",
  })
  async deleteAttachment(
    @graphql.Args() args: DeleteAttachmentArgs
  ): Promise<Attachment | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
